In [ ]:
# The pip install can take a minute
%pip install -q urllib3<2.0 datascience ipywidgets
import pyodide_http
pyodide_http.patch_all()

from datascience import *
%matplotlib inline
path_data = '../../../assets/data/'
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import numpy as np
import warnings
warnings.simplefilter(action='ignore')

## For statements

In [2]:
make_array('cat', 'dog', 'rabbit')

array(['cat', 'dog', 'rabbit'],
      dtype='<U6')

In [3]:
for pet in make_array('cat', 'dog', 'rabbit'):
    print('I love my ' + pet)

I love my cat
I love my dog
I love my rabbit


In [4]:
temporary = make_array('cat', 'dog', 'rabbit')

pet = temporary.item(0)
print('I love my ' + pet)

pet = temporary.item(1)
print('I love my ' + pet)

pet = temporary.item(2)
print('I love my ' + pet)

I love my cat
I love my dog
I love my rabbit


In [5]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [6]:
for i in np.arange(5):
    print(i)

0
1
2
3
4


In [7]:
for i in np.arange(5):
    print('Go Witsies')

Go Witsies
Go Witsies
Go Witsies
Go Witsies
Go Witsies


In [8]:
s = make_array(2, 3)
s

array([2, 3], dtype=int64)

In [9]:
np.append(s, 4)

array([2, 3, 4], dtype=int64)

In [10]:
s

array([2, 3], dtype=int64)

In [12]:
s + 3

array([5, 6, 7], dtype=int64)

In [13]:
s

array([2, 3, 4], dtype=int64)

In [11]:
s = np.append(s, 4)
s

array([2, 3, 4], dtype=int64)

In [ ]:
result = make_array(2, 3, 4)
for i in np.arange(5):
    result = np.append(result, 10 * i)
result

## Simulating heads in 100 coin tosses

In [14]:
coin = make_array('heads', 'tails')
coin

array(['heads', 'tails'],
      dtype='<U5')

In [18]:
sum(np.random.choice(coin, 100) == 'heads')

53

In [19]:
# Simulate one outcome

def num_heads(n):
    return sum(np.random.choice(coin, n) == 'heads')

In [22]:
# Simulate one outcome
num_heads(1)

0

In [23]:
# Decide how many times you want to repeat the experiment
repetitions = 10000
num_heads(repetitions)

4964