In [ ]:
# The pip install can take a minute
%pip install -q urllib3<2.0 datascience ipywidgets
import pyodide_http
pyodide_http.patch_all()

from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action='ignore')

## Comparison ##

In [2]:
3 > 1

True

In [3]:
type(3 > 1)

bool

In [5]:
True

False

In [6]:
true

NameError: name 'true' is not defined

(We see that capitalization matters.)

In [7]:
3 = 3

SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='? (3802935557.py, line 1)

In [8]:
3 == 3.0

True

In [11]:
10 != 2

True

In [12]:
x = 14
y = 3

In [14]:
x > 15

False

In [15]:
12 < x

True

In [16]:
x < 20

True

In [17]:
12 < x < 20

True

In [18]:
10 < x-y < 13

True

In [19]:
x > 13 and y < 3.14159

True

(The comparison `12 < x < 20` is equivalent to `12 < x and x < 20`.)

## Comparisons with arrays

In [21]:
pets = make_array('cat', 'cat', 'dog', 'cat', 'dog', 'rabbit')
pets

array(['cat', 'cat', 'dog', 'cat', 'dog', 'rabbit'],
      dtype='<U6')

In [22]:
pets == 'cat'

array([ True,  True, False,  True, False, False], dtype=bool)

In [24]:
1 + 1 + 0 + 1 + 0 + 0

3

In [23]:
sum(make_array(True, True, False, True, False, False))

3

In [25]:
sum(pets == 'dog')

2

In [26]:
np.count_nonzero(pets == 'dog')

2

In [27]:
x = np.arange(20, 31)
x

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [28]:
x > 28

array([False, False, False, False, False, False, False, False, False,
        True,  True], dtype=bool)

In [29]:
sum(x > 28)

2

## Conditional Statements

In [41]:
x = 20

In [42]:
if x >= 18:
    print('You can legally vote.')

You can legally vote.


In [43]:
if x >= 21:
    print('You can legally drink.')

In [44]:
def age(x):
    if x >= 18:
        return 'You can legally vote.'
    if x >= 21:
        return 'You can legally drink.'

In [45]:
age(3)

In [46]:
age(20)

'You can legally vote.'

In [47]:
age(25)

'You can legally vote.'

In [48]:
def age(x):
    if x >= 21:
        return 'You can legally vote and drink.'
    elif x >= 18:
        return 'You can legally vote.'
    else:
        return 'You can legally drink milk.'

In [49]:
age(3)

'You can legally drink milk.'

In [50]:
age(20)

'You can legally vote.'

In [51]:
age(23)

'You can legally vote and drink.'

In [52]:
trip = Table().read_table('trip.csv')
trip.show(3)

In [54]:
def trip_kind(start, end):
    if start == end:
        return 'round trip'
    else:
        return 'one way'

In [55]:
kinds = trip.with_column('Trip Kind', trip.apply(trip_kind, 'Start Station', 'End Station'))
kinds.show(3)

In [ ]:
kinds.where('Duration', are.below(600)).pivot('Trip Kind', 'Start Station')

## Simulation

Let's play a game: we each roll a die. 

If my number is bigger: you pay me R 1000.00.

If they're the same: we do nothing.

If your number is bigger: I pay you R 1000.00.

Steps:
1. Find a way to simulate two dice rolls.
2. Compute how much money we win/lose based on the result.
3. Do steps 1 and 2 10,000 times.

### Conditional Statements

In [ ]:
# Work in progress
def one_round(my_roll, your_roll):
    if my_roll > your_roll:
        return 1000

In [ ]:
one_round(4, 3)

In [ ]:
one_round(2, 6)

In [ ]:
# Final correct version
def one_round(my_roll, your_roll):
    if my_roll > your_roll:
        return 1000
    elif your_roll > my_roll:
        return -1000
    elif your_roll == my_roll:
        return 0

In [ ]:
one_round(1, 1)

In [ ]:
one_round(6, 5)

In [ ]:
one_round(7, -1)